Conta_custo = {
    "40372": {"nome": "PREMIOS E GRATIFICACOES", "natureza": ["C-PREMIOS/INCENTIVOS", "C-DO IT", "C-PREMIOS / INCENTIVOS", "C-PREMIOS / INCENTIVOS"]},
    "40373": {"nome": "SEGURO DE VIDA EM GRUPO", "natureza": ["SEGURO DE VIDA"]},
    "40375": {"nome": "ASSISTENCIA MEDICA / ODONTOLOGICA", "natureza": ["ASSISTENCIA MEDICA", "ASSISTENCIA MDICA", "ASSISTENCIA ODONTOLOGICA", "ASSISTENCIA ODONT", "ASSISTNCIA MDICA - CLT", "ASSISTNCIA MDICA - INTERNOS", "ASSISTNCIA ODONTOLGICA - CLT"]},
    "40391": {"nome": "MEDICINA OCUPACIONAL", "natureza": ["PCMSO"]},
    "40541": {"nome": "PARCEIROS OPERACIONAIS", "natureza": ["C-COLIGADA / TAXA ADM"]},
    "40402": {"nome": "LANCHES E REFEICOES", "natureza": ["C-ALIMENTACAO", "C-COFFEE BREAK"]},
    "40403": {"nome": "VIAGENS E ESTADAS", "natureza": ["C-HOSPEDAGEM", "D-HOSPEDAGEM", "C-AEREO", "C-PASSAGEM RODOVIARIA"]},
    "40408": {"nome": "FRETES E CARRETOS", "natureza": ["C-MOTOBOY", "C-TRANSPORTADORA", "COLIGADA / TRANSPORTADORA"]},
    "40409": {"nome": "MATERIAL DE CONSUMO", "natureza": ["C-MATERIAL DE APOIO"]},
    "40411": {"nome": "UNIFORMES E EQUIPAMENTOS DE SEGURANÇA", "natureza": ["C-UNIFORME/MATERIAL DE TRABALHO"]},
    "40413": {"nome": "TELECOMUNICACOES E INTERNET", "natureza": ["C-TELEFONE CELULAR", "C-TELEFONIA CELULAR", "C-TEEFONE CELULAR"]},
    "40414": {"nome": "LOCACAO DE VEICULOS", "natureza": ["C-LOCACAO DE VEICULO", "D-LOCACAO DE VEICULO"]},
    "40415": {"nome": "LOCACOES EM GERAL", "natureza": ["C-ALUGUEL DE EQUIPAMENTO", "C-LOCACAO DE SALA", "D-ALUGUEL DE EQUIPAMENTO"]},
    "40416": {"nome": "SERVIÇOS GRÁFICOS/EDIÇÃO/CRIAÇÃO", "natureza": ["EQUIPAMENTOS DE AUDIO", "C-MATERIAL GRAFICO, D-MATERIAL GRAFICO", "C-MATERIAL GRAFICO"]},
    "40419": {"nome": "MANUTENÇÃO E DESPESAS COM VEÍCULOS", "natureza": ["C-MANUTENCAO DE CARRO", "C - MANUTENO DE CARRO"]},
    "40420": {"nome": "CONDUÇÃO, ESTACIONAMENTO E PEDÁGIOS", "natureza": ["C-TAXI", "C-PEDAGIO", "C-ESTACIONAMENTO"]},
    "40421": {"nome": "CORREIOS E MALOTES", "natureza": ["C-CORREIO"]},
    "40422": {"nome": "SERVIÇOS/MATERIAL DE INFORMÁTICA", "natureza": ["C-SERVIÇOS DE INFORMATICA", "D-SERVIÇOS DE INFORMATICA", "C-SERVICOS DE INFORMATICA", "D-SERVICOS DE INFORMATICA"]},
    "40423": {"nome": "LEGAIS/CÓPIAS E AUTENTICAÇÕES", "natureza": ["C-AUTENTICAÇÕES E CÓPIAS", "C-AUTENTICACOES E COPIAS", "D-AUTENTICACOES E COPIAS"]},
    "40426": {"nome": "CURSOS E TREINAMENTOS", "natureza": ["D-CURSO DgE FORMAÇÃO PROFISSIONAL", "C-CURSO DE FORMAÇÃO PROFISSIONAL", "D-CURSO DE FORMACAO PROFISSIONAL", "C-CURSO DE FORMACAO PROFISSIONAL"]},
    "40428": {"nome": "PROMOÇÕES FESTAS E EVENTOS", "natureza": ["C-EVENTOS E FEIRAS"]},
    "40442": {"nome": "MANUTENÇÃO DAS INSTALAÇÕES/CELULARES", "natureza": ["C-Conservacao e Manutencao de equipamentos", "C-Conservção e Manutenção de equipamentos", "C - Conservao e Manuteno de Equipamentos"]},
    "40401": {"nome": "COMBUSTÍVEIS E LUBRIFICANTES", "natureza": ["C-COMBUSTIVEL", "D-COMBUSTIVEL"]},
    "40445": {"nome": "RECRUTAMENTO E SELEÇÃO", "natureza": ["C-ANTECEDENTES", "D-ANTECEDENTES"]},
    "50360": {"nome": "LEGAIS/CÓPIAS E AUTENTICAÇÕES", "natureza": ["C-AUTENTICAÇÕES E CÓPIAS"]},
    "40448": {"nome": "APARELHOS CELULARES", "natureza": ["C-APARELHO CELULAR", "D-APARELHO CELULAR"]},
    "50462": {"nome": "Multa de Trânsito", "natureza": ["C - Multa de Trnsito"]},
    "50385": {"nome": "Taxas, tarifas e afins", "natureza": ["C-TAXA ADMINISTRATIVAS", "D-TAXA ADMINISTRATIVAS", "D-TAXA ADMINISTRATIVA", "C-TAXA ADMINISTRATIVA"]},
    "40447": {"despesa": "HONORÁRIOS ADVOCATÍCIOS", "natureza": ["D-HONORÁRIOS ADVOCATICIO", "D-CUSTAS PROCESSUAIS", "D-HONORARIO ADVOCATICIO", "D-HONORARIO PERICIAIS", "D-HONORARIOS PERICIAIS"]},
    "40389":{"nome": "CB", "natureza": ["CB"]},
    "40376":{"nome": "VA", "natureza": ["VA"]},
    "40390":{"nome": "VR", "natureza": ["VR"]},
    "40377":{"nome": "AJ", "natureza": ["AJ", "VT", "PJ"]},
    "40543":{"nome": "OB", "natureza": ["OB"]},
    "50385":{"nome": "Taxa", "natureza": ["Taxa"]},


}

conta_despesa = {
    "50159": {"despesa": "PREMIOS E GRATIFICACOES", "natureza": ["C-PREMIOS/INCENTIVOS", "D-PREMIOS/INCENTIVOS", "C-DO IT"]},
    "50160": {"despesa": "SEGURO DE VIDA EM GRUPO", "natureza": ["SEGURO DE VIDA"]},
    "50179": {"despesa": "ASSISTENCIA MEDICA E ODONTOLOGICA", "natureza": ["ASSISTNCIA MDICA", "ASSISTENCIA MEDICA", "ASSISTENCIA ODONTOLOGICA", "ASSISTENCIA ODONT", "ASSISTNCIA MDICA - INTERNOS"]},
    "50201": {"despesa": "MANUTENÇÃO DE INSTALAÇÕES", "natureza": ["CONSERVACAO E MANUTE", "CONSERVACAO E MANUTENCAO", "D-CONSERVACAO E MANUTENCAO", "C-CONSERVACAO E MANUTENCAO"]},
    "50205": {"despesa": "FRETES E CARRETOS", "natureza": ["D-MOTOBOY"]},
    "50208": {"despesa": "CURSOS E TREINAMENTOS", "natureza": ["D-CURSOS DE FORMAÇÃO PROFISSIONAL", "D-CURSO DE FORMACAO PROFISSIONAL", "D-ESTAGIARIO"]},
    "50210": {"despesa": "HONORÁRIOS ADVOCATÍCIOS", "natureza": ["D-HONORÁRIOS ADVOCATICIO", "D-CUSTAS PROCESSUAIS", "D-HONORARIO ADVOCATICIO"]},
    "50211": {"despesa": "HONORÁRIOS CONTÁBEIS", "natureza": ["ASSESSORIA CONTÁBIL", "D-ASSESSORIA CONTABIL"]},
    "50212": {"despesa": "RECRUTAMENTO E SELEÇÃO", "natureza": ["D-ANTECEDENTES"]},
    "50213": {"despesa": "AUDITORIA E CONSULTORIA", "natureza": ["D-CONSULTORIA"]},
    "50216": {"despesa": "SERVIÇOS GRÁFICOS/EDIÇÃO/CRIAÇÃO", "natureza": ["C-MATERIAL GRÁFICO", "C-EQUIPAMENTOS DE ÁUDIO"]},
    "50217": {"despesa": "MEDICINA OCUPACIONAL", "natureza": ["PCMSO"]},
    "50920": {"despesa": "SERVIÇOS PRESTADOS PJ'S", "natureza": ["D-MÃO OBRA TERCEIRO"]},
    "50222": {"despesa": "LOCACAO DE EQUIPAMENTO PAGO A PJ", "natureza": ["D-ALUGUEL DE EQUIPAMENTO", "C-ALUGUEL DE EQUIPAMENTO"]},
    "50223": {"despesa": "LOCACAO DE VEICULO", "natureza": ["D-LOCACAO DE VEICULO"]},
    "50356": {"despesa": "TELECOMUNICAÇÕES E INTERNET", "natureza": ["C-TELEFONE CELULAR", "D-INTERNET", "C-INTERNET", "D-TELEFONE CELULAR", "TELEFONE FIXO", "D-TELEFONIA CELULAR"]},
    "50360": {"despesa": "XEROX E AUTENTICAÇÕES", "natureza": ["D-AUTENTICAÇÕES E CÓPIAS", "D-AUTENTICACOES E COPIAS", "C-AUTENTICACOES E COPIAS"]},
    "50364": {"despesa": "CORREIOS E MALOTES", "natureza": ["C-CORREIOS", "D-CORREIO", "C-CORREIO"]},
    "50367": {"despesa": "MATERIAL DE APOIO", "natureza": ["C-MATERIAL DE APOIO", "D-MATERIAL DE APOIO"]},
    "50368": {"despesa": "MATERIAL DE LIMPEZA", "natureza": ["C-MATERIAL DE LIMPEZA", "D-MATERIAL DE LIMPEZA"]},
    "50203": {"despesa": "MANUTENÇÃO DE VEÍCULOS", "natureza": ["MANUTENCAO DE CARRO", "D-MANUTENCAO DE CARRO"]},
    "50244": {"despesa": "LICENCIAMENTO DE VEÍCULOS", "natureza": ["LICENCIAMENTO DE VEÍCULOS"]},
    "50361": {"nome": "VIAGENS E ESTADAS", "natureza": ["C-HOSPEDAGEM", "D-HOSPEDAGEM", "C-AEREO", "C-PASSAGEM RODOVIARIA", "C-AEREO", "D-AEREO", "D-SEGURO VIAGEM"]},
    "50375": {"nome": "UNIFORMES E EQUIPAMENTOS DE SEGURANÇA", "natureza": ["UNIFORME/MATERIAL DE TRABALHO", "D-UNIFORME/MATERIAL DE TRABALHO"]},
    "50352": {"nome": "COMBUSTÍVEIS E LUBRIFICANTES", "natureza": ["C-COMBUSTÍVEL", "D-COMBUSTÍVEL"]},
    "50388": {"nome": "PROMOÇÕES FESTAS E EVENTOS", "natureza": ["C-EVENTOS E FEIRAS", "D-EVENTOS/CONFRATERNIZAO"]},
    "50216": {"nome": "SERVIÇOS GRÁFICOS/EDIÇÃO/CRIAÇÃO", "natureza": ["EQUIPAMENTOS DE AUDIO", "C-MATERIAL GRAFICO", "D-MATERIAL GRAFICO"]},
    "50462": {"nome": "Multa de Trânsito", "natureza": ["C - Multa de Trnsito"]},
    "50385": {"nome": "Taxas, tarifas e afins", "natureza": ["C-TAXA ADMINISTRATIVAS", "D-TAXA ADMINISTRATIVAS"]},
    "50363": {"nome": "CONDUÇÃO, ESTACIONAMENTO E PEDÁGIOS", "natureza": ["C-TAXI", "C-PEDAGIO", "C-ESTACIONAMENTO", "D-TAXI", "D-PEDAGIO", "D-ESTACIONAMENTO"]},
    "50377": {"nome": "SERVIÇOS/MATERIAL DE INFORMÁTICA", "natureza": ["C-SERVICOS DE INFORMATICA", "D-SERVICOS DE INFORMATICA", "D-SERVICOS DE INFORMATICA"]},
    "50261": {"nome": "Manutenção/Conservação do Prédio", "natureza": ["D-CONSERVAO DE MANUTENO PREDIAL", "C-CONSERVAO DE MANUTENO PREDIAL", "D - Conservao e Manuteno de Equipamentos"]},
    "50232":{"nome": "CB", "natureza": ["CB"]},
    "50231":{"nome": "VA", "natureza": ["VA"]},
    "50234":{"nome": "VR", "natureza": ["VR"]},
    "50922":{"nome": "AJ", "natureza": ["AJ", "PJ"]},
    "50178":{"nome": "VT", "natureza": ["VT"]},
    "50323":{"nome": "OB", "natureza": ["OB"]},
    "50385":{"nome": "Taxa", "natureza": ["Taxa"]},
}

try:
    mapeamento_custo = {natureza: conta for conta, detalhes in Conta_custo.items() for natureza in detalhes['natureza']}
    mapeamento_despesa = {natureza: conta for conta, detalhes in conta_despesa.items() for natureza in detalhes['natureza']}
except KeyError:
    print("ERRO: Verifique a estrutura dos dicionários de contas. Chave 'natureza' não encontrada.")
    mapeamento_custo = {}
    mapeamento_despesa = {}